# Generated by Django 2.0.3 on 2018-04-08 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180408_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 21, 50, 50, 643286, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
